### PR TITLE
Added DFS deprecation information for 2023.1

### PR DESCRIPTION
**Pull request by david-staniec-octopus**
As per title

### CODE REVIEW

**Comment by david-staniec-octopus** [comment]
Fixes https://github.com/OctopusDeploy/Issues/issues/8046

**Review by sburmanoctopus — APPROVED** [review]
Looks fine to me. But it might be worth getting @irynasemenova to have a read just to be sure 🙂

**Comment by david-staniec-octopus** [comment]
[sc-40252](https://app.shortcut.com/octopusdeploy/story/40252/update-the-deprecations-page)

**Comment by david-staniec-octopus** [comment]
Fixes https://github.com/OctopusDeploy/Issues/issues/8046

**Pull request merged**
