### PR TITLE
2 minor updates on the Run a runbook CLI page

### PR DESCRIPTION
**Pull request by donnybell**
Fixed --project=VALUE requirement
Fixed  --variable=VALUE from "Label:Value" to "Name:Value"

### CODE REVIEW

**Comment by harrisonmeister** [comment]
@donnybell - the cli pages automatically get updated from the commands (a TC build creates PR) so this change would get undone I think. It might be worth checking with F&M if we can get the actual code changed to reflect your changes?

**Comment by matt-richardson** [comment]
Code in question is at https://github.com/OctopusDeploy/OctopusCLI/blob/master/source/Octopus.Cli/Commands/Runbooks/RunRunbookCommand.cs#L34.

**Comment by donnybell** [comment]
> @donnybell - the cli pages automatically get updated from the commands (a TC build creates PR) so this change would get undone I think. It might be worth checking with F&M if we can get the actual code changed to reflect your changes?

Thanks @harrisonmeister, I'll create a problem ticket in Zendesk about this and send it over. Thanks!

**Comment by harrisonmeister** [comment]
Closing for now as I've raised https://github.com/OctopusDeploy/OctopusCLI/pull/116

**Pull request closed without merging**
