### PR TITLE
Fixing typo

### PR DESCRIPTION
**Pull request by briggs-octo**

### CODE REVIEW

**Review by harrisonmeister — APPROVED** [review]

**Comment by harrisonmeister** [comment]
@briggs-octo - can you sign the CLA otherwise the PR wont merge :)

**Comment by briggs-octo** [comment]
Hmmm...I've already signed the CLA in the past. Weird. Where can I redo this @harrisonmeister? Not seeing any options for it on the PR :frowning_face:

**Comment by briggs-octo** [comment]
Yeah, says it's already been signed...sorry this is being a pain, but thanks for your help!

image

**Comment by harrisonmeister** [comment]
> Yeah, says it's already been signed...sorry this is being a pain, but thanks for your help!
> 
> image

Oh weird, I'll see if I can figure it out

**Pull request merged**
