### PR TITLE
Add worker variables and restrictions

### PR DESCRIPTION
**Pull request by MichaelJCompton**
**still needs a screenshot on the variables page**

Related to OctopusDeploy/Issues#5842

### CODE REVIEW

**Comment by wordlee** [comment]
Just noting the build error should go away when this is merged. The error is complaining about a page that is created in this PR being missing.

**Comment by tothegills** [comment]
[Workers vNext](https://trello.com/c/ypel7qog/17-workers-vnext)

**Comment by tothegills** [comment]
[Workers vNext](https://trello.com/c/ypel7qog/17-workers-vnext)

**Comment by droyad** [comment]
[Worker Pool Variables](https://trello.com/c/fnMnnWHU/2796-worker-pool-variables)

**Comment by wordlee** [comment]
Hi @droyad, you probably spotted this, but just in case, please note the variables section of the docs has move from docs/deployment-process/variables/ to docs/projects/variables to allow for the fact that variables are available in both deployment processes and runbooks (which are both contained in projects).

**Comment by droyad** [comment]
Closing this and picking across the changes that are needed

**Pull request closed without merging**
