### PR TITLE
Automatically update credits file with latest licence information

### PR DESCRIPTION
**Pull request by Octobob**

### CODE REVIEW

**Review by harrisonmeister — APPROVED** [review]

**Comment by matt-richardson** [comment]
@harrisonmeister - these ones need a ✔️ from MikeN or @jburger before merging, as they are a bit of an sanity check around our component usage.
We [used to](https://github.com/OctopusDeploy/docs/pull/1085) include "what to do with this pr" but it looks like it got dropped somewhere along the track. @uglybugger, can you look at that under warranty please?

**Comment by harrisonmeister** [comment]
Ah sorry, my bad. I did wonder why they were tagged. That now explains it 🤦

**Comment by harrisonmeister** [comment]
The credits.template.md file is also being displayed in the docs as it has an extension of `.md`. Wasnt sure if that was something you could look at too @uglybugger ?

**Comment by uglybugger** [comment]
> @harrisonmeister - these ones need a ✔️ from MikeN or @jburger before merging, as they are a bit of an sanity check around our component usage.
> We [used to](https://github.com/OctopusDeploy/docs/pull/1085) include "what to do with this pr" but it looks like it got dropped somewhere along the track. @uglybugger, can you look at that under warranty please?

Bleh. Yep, my bad. I'll plan to take a look sometime in the next day or two after the cycle has kicked off properly.

**Comment by uglybugger** [comment]
> The credits.template.md file is also being displayed in the docs as it has an extension of `.md`. Wasnt sure if that was something you could look at too @uglybugger ?

Will do. Thanks for the heads-up :)

**Comment by uglybugger** [comment]
Update: ETA on this is early next week.

**Comment by uglybugger** [comment]
New pull requests created by that build now have nice descriptions again.

[Here's the latest PR](https://github.com/OctopusDeploy/docs/pull/1181) as an example.

Sorry it took so long to get this last little bit fixed.

**Pull request merged**
