### PR TITLE
Adds region failure to the Disaster Recovery tables

### PR DESCRIPTION
**Pull request by michaelnoonan**
I was looking at this with @alexrolleyoctopus and @RayAtOctopus and found the region failure scenario was buried in a section at the end of the page. I expected to have a region failure estimate in the same tables as data center failure.

I've added the RTO estimate to the table to more clearly show how the scenarios escalate, along with a pointer to the region failure section.

### CODE REVIEW

**Review by michaelnoonan — COMMENTED** [review]
Adds majeure to dictionary

**Comment by JonPHardy57** [comment]
I am OK with the changes but have not approved as only 1 is required and Ray probably needs the opportunity to review.

**Review by JonPHardy57 — APPROVED** [review]
All good by me.

**Review by alexrolleyoctopus — APPROVED** [review]
Approved

**Pull request merged**
