### PR TITLE
Add Kubernetes agent diagrams

### PR DESCRIPTION
**Pull request by nikita-dergilev**
Added Rob's diagrams to the Kubernetes target overview and Kubernetes agent overview pages

### CODE REVIEW

**Comment by APErebus** [comment]
Do we need to manually update the `modDate` on the docs files?

**Comment by nikita-dergilev** [comment]
> Do we need to manually update the `modDate` on the docs files?

@APErebus , to be honest, I don't know, maybe. @thekatstevens, do you know the answer?

**Comment by zentron** [comment]
I think this looks pretty good. I'm not sure if we will need more context around the components diagram, but what you have might be sufficient for now.

**Review by zentron — APPROVED** [review]
I think this looks pretty good. I'm not sure if we will need more context around the components diagram, but what you have might be sufficient for now.

**Review by thekatstevens — APPROVED** [review]
Looks fine to me, if the images load properly when you run it locally then 👍 

I'll tweak a couple of links while we're editing too

**Comment by steve-fenton-octopus** [comment]
@APErebus @nikita-dergilev If you make a solid change to the content, it's worth updating the `modDate`.

We use this to signal to Google that there's a change worth re-indexing, which is why we don't update it automatically. If you signal low-change or no-change updates, they stop listening to your signal.

**Comment by nikita-dergilev** [comment]
@steve-fenton-octopus , @APErebus , @thekatstevens , @zentron , thanks a lot! Merged :-)

**Pull request merged**
