### PR TITLE
Removed duplicate dependsOn property

### PR DESCRIPTION
**Pull request by bjcull**
Someone has accidentally added a duplicate of the dependsOn node. They both had exactly the same data.

### CODE REVIEW

**Comment by matt-richardson** [comment]
Hi Ben

Thanks for the PR - appreciate it.

How did the install go? All work as expected? We've only done a soft (re-)launch of it so far, so any feedback gratefully received!

**Comment by bjcull** [comment]
Hey Matt,

Just working through it at the moment. I've got a hurdle, but I'll throw
the details into a support forum post, Damo's having a quick look for me as
well.

Cheers,

Ben

**Comment by bjcull** [comment]
Okie doke, posted my question and answer to the forum:
http://help.octopusdeploy.com/discussions/problems/51694-tentacle-url-set-to-machine-name-instead-of-fully-qualified-doimain-name

I'll change to a polling tentacle for now so I can continue on. I'll let
you know how it all goes once I'm fully up and running.


Cheers,

Ben

**Comment by matt-richardson** [comment]
Thanks, @bjcull!

**Pull request merged**
