### PR TITLE
Daniel tentacle requirements update

### PR DESCRIPTION
**Pull request by danielfischeroctopus**

### CODE REVIEW

**Review by zentron — APPROVED** [review]
Thanks @danielfischeroctopus

**Review by zentron — CHANGES_REQUESTED** [review]
@danielfischeroctopus are we able to be more specific about which LTSC we support?

**Review by zentron — APPROVED** [review]
Thanks for the update @danielfischeroctopus

**Review by steve-fenton-octopus — APPROVED** [review]
LGTM!

**Pull request merged**
