### PR TITLE
Change metrics command to deprecated

### PR DESCRIPTION
**Pull request by harrisonmeister**

### CODE REVIEW

**Review by charles-hague-octopus — APPROVED** [review]
Removed in 2020.5 as per https://octopus.com/downloads/compare?from=2020.1.10&to=2020.6.4855 and linked changes.

**Review by matt-richardson — APPROVED** [review]
Seems reasonable.
Do we want to say why?
Do we want to refer to a github issue or similar?
(not sure if the answer is yes to either of them, but thought it useful to ask)

**Comment by harrisonmeister** [comment]
> Seems reasonable.
> Do we want to say why?
> Do we want to refer to a github issue or similar?
> (not sure if the answer is yes to either of them, but thought it useful to ask)

I followed the convention I found with the [external-worker](https://octopus.com/docs/octopus-rest-api/octopus.server.exe-command-line/external-worker) command.

Thinking about this some more, would it be better to have the pages removed, and then link to a deprecated commands section?

**Comment by matt-richardson** [comment]
> > Seems reasonable.
> > Do we want to say why?
> > Do we want to refer to a github issue or similar?
> > (not sure if the answer is yes to either of them, but thought it useful to ask)
> 
> I followed the convention I found with the [external-worker](https://octopus.com/docs/octopus-rest-api/octopus.server.exe-command-line/external-worker) command.
> 
> Thinking about this some more, would it be better to have the pages removed, and then link to a deprecated commands section?

I'm not sure I've got answers here - I think I'll leave the decision with you on how to proceed.

That said, as I think about it, having a deprecated commands section might be useful:
* having it as a menu item might be a bit annoying "oh, yeah, that looks like what I need! oh. deprecated. boo."
* splitting it out to it's own page might cover customers on older versions better?

I'll leave the call with you - you spend much more time thinking about the docs experience than I do :)

**Comment by harrisonmeister** [comment]
Thanks @matt-richardson - I'll have a think on this 😄

**Comment by harrisonmeister** [comment]
For now, I'm going to merge this, and revisit at a later date

**Pull request merged**
