### PR TITLE
Updating cli docs for octopus.server.exe

### PR DESCRIPTION
**Pull request by Octobob**
An automated update of the command line docs for octopus.server.exe.

Created by TeamCity project 'Automated Documentation Updates::Update CLI Docs', build 81

### CODE REVIEW

**Comment by matt-richardson** [comment]
Erk. Not sure that this should've been merged. I think @slewis74 was concerned some of the values in there shouldn't have been - https://github.com/OctopusDeploy/docs/pull/510#pullrequestreview-281778900

**Comment by wordlee** [comment]
Thanks @matt-richardson! I've revert the commit. In future is it possible not to submit PRs for things that shouldn't be committed or is the process completely automated?

**Comment by matt-richardson** [comment]
Completely automated - not sure what the best approach is here... 🤔

**Comment by wordlee** [comment]
How about this, going forward, if there are old PRs for the same automated content, I'll either:
1. Close the old PR if there are no outstanding change requests/blockers on the old PR (the new PR is the thing to focus on) - the Credits page updates will likely fall into this category.
2. Close the new PR if there are outstanding change requests/blockers on the old PR (the old PR is still the thing to focus on).

**Comment by matt-richardson** [comment]
Sounds good - thanks for that. Sounds workable for now until we can come up with a better plan.

**Pull request merged**
