### PR TITLE
Adds documentation for the Deploy Raw Yaml Git Manifest and Glob Expression features

### PR DESCRIPTION
**Pull request by scme0**
I have moved the Raw Yaml section from the main Kubernetes page to a child page so that I could add extra information about the new Git Repository data source. I've also added some screen shots to give users a better idea of what we're talking about.

Finally, I've added a "Glob Expressions and Multiple Paths" section to show users how they can now use this field to specify their YAML files and a Glob Expression Cheat Sheet so users understand how to use Glob Expressions effectively.

[sc-44788]

### CODE REVIEW

**Comment by steve-fenton-octopus** [comment]
Hey @scme0 - is this PR ready for review now? The title is making me hesitate :)

**Comment by scme0** [comment]
Hey Steve, almost but not quite. I'm just finalising what features will actually be in glob patterns before finalising it and reviewing it myself.

**Comment by scme0** [comment]
@steve-fenton-octopus This is now ready for review if you want to take a look 👍  I've also asked my team to review to make sure I haven't missed anything obvious in the new features.

**Review by steve-fenton-octopus — APPROVED** [review]
LGTM!

**Pull request merged**
